# Generated by Django 5.2.7 on 2025-11-10 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplicacionParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Complicación')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Madre',
                'verbose_name_plural': 'Madres',
            },
        ),
        migrations.CreateModel(
            name='TipoAnalgesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Analgesia')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Parto')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_parto', models.DateTimeField(verbose_name='Fecha y Hora del Parto')),
                ('edad_gestacional_semanas', models.PositiveSmallIntegerField(verbose_name='Edad Gestacional (Semanas)')),
                ('personal_atiende', models.CharField(blank=True, max_length=255, verbose_name='Personal que Atiende')),
                ('uso_oxitocina', models.BooleanField(default=False, verbose_name='Uso de Oxitocina Profiláctica')),
                ('ligadura_tardia_cordon', models.BooleanField(default=False, verbose_name='Ligadura Tardía de Cordón (>60s)')),
                ('contacto_piel_a_piel', models.BooleanField(default=False, verbose_name='Contacto Piel a Piel')),
                ('complicaciones', models.ManyToManyField(blank=True, to='dashboard.complicacionparto', verbose_name='Complicaciones')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='dashboard.madre', verbose_name='Madre')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('tipo_analgesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tipoanalgesia', verbose_name='Tipo de Analgesia')),
                ('tipo_parto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tipoparto', verbose_name='Tipo de Parto')),
            ],
            options={
                'verbose_name': 'Registro de Parto',
                'verbose_name_plural': 'Registros de Partos',
                'ordering': ['-fecha_parto'],
            },
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1, verbose_name='Sexo')),
                ('peso_grs', models.PositiveSmallIntegerField(verbose_name='Peso (gramos)')),
                ('talla_cm', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Talla (cm)')),
                ('apgar_1_min', models.PositiveSmallIntegerField(verbose_name='APGAR al Minuto')),
                ('apgar_5_min', models.PositiveSmallIntegerField(verbose_name='APGAR a los 5 Minutos')),
                ('profilaxis_ocular', models.BooleanField(default=True, verbose_name='Profilaxis Ocular')),
                ('vacuna_hepatitis_b', models.BooleanField(default=True, verbose_name='Vacuna Hepatitis B')),
                ('parto_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='dashboard.registroparto')),
            ],
            options={
                'verbose_name': 'Recién Nacido',
                'verbose_name_plural': 'Recién Nacidos',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje del solicitante')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta')], default='pendiente', max_length=10)),
                ('timestamp_creacion', models.DateTimeField(auto_now_add=True)),
                ('timestamp_resolucion', models.DateTimeField(blank=True, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_correccion', to='dashboard.registroparto')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Corrección',
                'verbose_name_plural': 'Solicitudes de Corrección',
                'ordering': ['-timestamp_creacion'],
            },
        ),
    ]
