# Generated by Django 5.2.7 on 2025-11-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroparto',
            name='complicaciones',
        ),
        migrations.AddField(
            model_name='registroparto',
            name='complicaciones_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Complicaciones (descripción)'),
        ),
        migrations.DeleteModel(
            name='ComplicacionParto',
        ),
    ]
