# Generated by Django 5.2.7 on 2025-11-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_registroparto_complicaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madre',
            name='rut',
            field=models.CharField(db_index=True, max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='registroparto',
            name='fecha_parto',
            field=models.DateTimeField(db_index=True, verbose_name='Fecha y Hora del Parto'),
        ),
    ]
