# Generated by Django 5.2.7 on 2025-11-22 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_madre_rut_alter_registroparto_fecha_parto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_1_min',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='APGAR al Minuto'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_5_min',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='APGAR a los 5 Minutos'),
        ),
    ]
