# Generated by Django 5.2.7 on 2025-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_reciennacido_apgar_1_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciennacido',
            name='alimentacion_alta',
            field=models.CharField(choices=[('LME', 'Lactancia Materna Exclusiva'), ('LMixta', 'Lactancia Mixta'), ('Formula', 'Fórmula Artificial')], default='LME', max_length=20, verbose_name='Alimentación al Alta'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='anomalia_congenita',
            field=models.BooleanField(default=False, verbose_name='Presenta Anomalía Congénita'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='reanimacion',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('basica', 'Básica (Estimulación, Aspiración)'), ('avanzada', 'Avanzada (Ventilación, Masaje, Drogas)')], default='ninguna', max_length=20, verbose_name='Reanimación Neonatal'),
        ),
    ]
