# Generated by Django 5.2.7 on 2025-11-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_reciennacido_alimentacion_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='fallecida',
            field=models.BooleanField(default=False, verbose_name='Fallecida'),
        ),
        migrations.AddField(
            model_name='madre',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AddField(
            model_name='madre',
            name='fecha_fallecimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='alta_validada',
            field=models.BooleanField(default=False, verbose_name='Alta Validada (Supervisor)'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='fallecido',
            field=models.BooleanField(default=False, verbose_name='Fallecido'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='fecha_fallecimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
    ]
