# Generated by Django 5.2.7 on 2025-11-22 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_madre_fallecida_madre_fecha_alta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='responsable_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_madres', to=settings.AUTH_USER_MODEL, verbose_name='Médico Responsable (Alta/Defunción)'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='responsable_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_rn', to=settings.AUTH_USER_MODEL, verbose_name='Médico Responsable (Alta/Defunción)'),
        ),
    ]
