# Generated by Django 5.2.7 on 2025-11-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_madre_responsable_medico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='pertenece_pueblo_originario',
            field=models.BooleanField(default=False, verbose_name='Pertenece a Pueblo Originario'),
        ),
    ]
