# Generated by Django 5.2.7 on 2025-11-22 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('turno', models.CharField(choices=[('diurno', 'Turno Diurno'), ('nocturno', 'Turno Nocturno')], default='diurno', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_liderados', to=settings.AUTH_USER_MODEL, verbose_name='Doctor Líder')),
                ('miembros', models.ManyToManyField(related_name='equipos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Miembros del Equipo')),
            ],
        ),
    ]
